import React, { useState } from 'react'

const About = () => {
  const [activeTab, setActiveTab] = useState(1)
  const [showFAQ, setShowFAQ] = useState(false)
  const [testimonialIndex, setTestimonialIndex] = useState(0)

  const testimonials = [
    {
      quote:
        'AI Application Assistant transformed how I approach job applications. Highly recommended!',
      author: 'Jamie',
    },
    {
      quote: 'The cover letters generated were spot on. Saved me hours!',
      author: 'Taylor',
    },
    {
      quote:
        'Great for quick, professional applications. I loved the customization!',
      author: 'Alex',
    },
    {
      quote: 'This tool made my job hunt so much easier and more efficient!',
      author: 'Jordan',
    },
    {
      quote: "I've never felt more confident in my applications. Thank you!",
      author: 'Casey',
    },
    {
      quote:
        "The AI's understanding of industry-specific terminology is impressive.",
      author: 'Morgan',
    },
    // Add more testimonials here
  ]

  const nextTestimonial = () => {
    setTestimonialIndex((testimonialIndex + 1) % testimonials.length)
  }

  const previousTestimonial = () => {
    setTestimonialIndex(
      (testimonialIndex - 1 + testimonials.length) % testimonials.length
    )
  }

  const toggleFAQ = () => {
    setShowFAQ(!showFAQ)
  }

  return (
    <div className='about-container'>
      <div className='about-section'>
        <h1>About AI Application Assistant</h1>
        <p>
          Keep reading to learn more about what our platform is capeable of.
        </p>
      </div>

      {/* Embedded Video or Demo Section */}
      <section className='video-demo-section'>
        <h2>See It In Action</h2>
        <iframe
          src='https://www.youtube.com/watch?v=1bJABKCcagg&t=72s'
          frameborder='0'
          allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture'
          allowfullscreen
          className='demo-video'></iframe>
      </section>

      {/* Interactive How It Works Section */}
      <div className='how-it-works'>
        <h2>How It Works</h2>
        <div className='tabs'>
          <button
            onClick={() => setActiveTab(1)}
            className={activeTab === 1 ? 'active' : ''}>
            Step 1
          </button>
          <button
            onClick={() => setActiveTab(2)}
            className={activeTab === 2 ? 'active' : ''}>
            Step 2
          </button>
          <button
            onClick={() => setActiveTab(3)}
            className={activeTab === 3 ? 'active' : ''}>
            Step 3
          </button>
          <button
            onClick={() => setActiveTab(4)}
            className={activeTab === 4 ? 'active' : ''}>
            Step 4
          </button>
        </div>
        <div className='tab-content'>
          {activeTab === 1 && (
            <p>
              Input Job Details: Enter the job title, company name, and
              location.
            </p>
          )}
          {activeTab === 2 && (
            <p>
              Paste Job Description: Copy the job description to provide
              context.
            </p>
          )}
          {activeTab === 3 && (
            <p>
              Copy & Paste Resume: Paste a copy of your resume for a
              personalized touch.
            </p>
          )}
          {activeTab === 4 && (
            <p>
              Create the Letter: Submit the form and receive a tailored cover
              letter in usually less than a minute.
            </p>
          )}
        </div>
      </div>

      {/* FAQ Section with More Questions and Answers */}
      <div className='faq-section'>
        <h2>Frequently Asked Questions</h2>
        <button onClick={toggleFAQ} className='faq-toggle'>
          {showFAQ ? 'Hide FAQs' : 'Show FAQs'}
        </button>
        {showFAQ && (
          <div className='faq-list'>
            <p>
              <b>How is each cover letter personalized to my profile?</b>
              <br />
              Our AI analyzes your resume and aligns it with the job description
              to create a unique cover letter.
            </p>
            <p>
              <b>What AI technology is used in the application?</b>
              <br />
              We use advanced NLP algorithms to understand and match your skills
              with job requirements.
            </p>
            <p>
              <b>Is my data secure?</b>
              <br />
              Yes, we prioritize data security and confidentiality in our
              application.
            </p>
            <p>
              <b>Can I customize the cover letter generated by the AI?</b>
              <br />
              Yes, our AI provides a strong starting point, but you can
              customize and tweak the cover letter to your liking.
            </p>
            <p>
              <b>How long does it take to generate a cover letter?</b>
              <br />
              Our AI works quickly! It typically takes just a few seconds to
              generate a personalized cover letter.
            </p>
            <p>
              <b>
                Do you offer support if I encounter issues with the application?
              </b>
              <br />
              Absolutely! We have a dedicated support team ready to assist you
              with any issues or questions.
            </p>
            <p>
              <b>Is AI Application Assistant suitable for all industries?</b>
              <br />
              Yes, our AI is designed to cater to a wide range of industries by
              adapting to various job descriptions and resume styles.
            </p>
            <p>
              <b>How does your AI ensure the cover letter is free of errors?</b>
              <br />
              Our AI incorporates advanced error-checking algorithms to ensure
              your cover letter is grammatically correct and free of typos.
            </p>
            <p>
              <b>
                Can I use AI Application Assistant if I have a non-traditional
                career path?
              </b>
              <br />
              Definitely. Our AI is adept at handling diverse career backgrounds
              and can highlight your unique experiences effectively.
            </p>
            <p>
              <b>
                Is there a limit to how many cover letters I can generate with a
                subscription?
              </b>
              <br />
              With a subscription, you can generate an unlimited number of cover
              letters during the subscription period.
            </p>
            <p>
              <b>
                What makes AI Application Assistant different from other cover
                letter tools?
              </b>
              <br />
              Our tool uniquely aligns your skills and experiences with specific
              job requirements using advanced AI, offering a more personalized
              approach.
            </p>
            <p>
              <b>
                Can I save and access my previously generated cover letters?
              </b>
              <br />
              Yes, all your generated cover letters are saved in your account
              for easy access and modification.
            </p>
            <p>
              <b>
                Can I integrate this tool with other job application platforms?
              </b>
              <br />
              Currently, our application operates independently, but we're
              working on integrating with popular job application platforms.
            </p>
            <p>
              <b>Do you offer guidance on how to improve my resume?</b>
              <br />
              While our primary focus is on cover letters, we provide basic tips
              and suggestions for improving your resume.
            </p>
          </div>
        )}
      </div>

      {/* Interactive Testimonials Section */}
      <div className='testimonials-section'>
        <h2>User Testimonials</h2>
        <div className='testimonial'>
          <blockquote>
            "{testimonials[testimonialIndex].quote}" -{' '}
            {testimonials[testimonialIndex].author}
          </blockquote>
          <div className='testimonial-buttons'>
            <button onClick={previousTestimonial}>&lt;</button>
            <button onClick={nextTestimonial}>&gt;</button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default About
